Models/Services.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace RazorPages.Models
{
    public class Services
    {
        public int ID { get; set; }
        public string Name { get; set; }
        //Spa Services:  full-day, half-day,two-hour, one-hour
        public string Classification { get; set; } = "Full";
        [Range(35, 1000)]
        public double Fee { get; set; } = 200.00;
    }
}

Controllers/ServiceController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using RazorPages.Models;

namespace RazorPages.Controllers
{
    public class ServiceController : Controller
    {
        private readonly SpaContext _context;

        public ServiceController(SpaContext context)
        {
            _context = context;
        }

        // GET: Service
        public async Task<IActionResult> Index()
        {
            return View(await _context.Services.ToListAsync());
        }
        //GET
        public IActionResult Descriptions()
        {
            ViewBag.Classifications = _context.Services.ToList();
            return View();
        }
        //POST
        [HttpPost]
        public IActionResult Descriptions(Services model)
        {

            var viewName = "";
            switch(model.Classification)
            {
                case "Full":
                    viewName = "full";
                    break;
                case "Half":
                    viewName = "half";
                    break;
                case "Two":
                    viewName = "two";
                    break;
                case "One":
                    viewName = "one";
                    break;
                default:
                    viewName = "other";
                    break;

            }
            return View(viewName,model);
        }

        // GET: Service/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var services = await _context.Services
                .FirstOrDefaultAsync(m => m.ID == id);
            if (services == null)
            {
                return NotFound();
            }
            ViewBag.fee = services.Fee;
            return View(services);
        }

        // GET: Service/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Service/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ID,Name,Classification,Fee")] Services services)
        {
            if (ModelState.IsValid)
            {
                _context.Add(services);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(services);
        }

        // GET: Service/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var services = await _context.Services.FindAsync(id);
            if (services == null)
            {
                return NotFound();
            }
            return View(services);
        }

        // POST: Service/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ID,Name,Classification,Fee")] Services services)
        {
            if (id != services.ID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(services);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ServicesExists(services.ID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(services);
        }

        // GET: Service/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var services = await _context.Services
                .FirstOrDefaultAsync(m => m.ID == id);
            if (services == null)
            {
                return NotFound();
            }

            return View(services);
        }

        // POST: Service/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var services = await _context.Services.FindAsync(id);
            _context.Services.Remove(services);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        public IActionResult all()
        {
            return View();
        }

        private bool ServicesExists(int id)
        {
            return _context.Services.Any(e => e.ID == id);
        }
    }
}

Views/Service/Create.cshtml
@model RazorPages.Models.Services

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Services</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Classification" class="control-label"></label>
                <input asp-for="Classification" class="form-control" />
                <span asp-validation-for="Classification" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Fee" class="control-label"></label>
                <input asp-for="Fee" class="form-control" />
                <span asp-validation-for="Fee" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Service/Delete.cshtml
@model RazorPages.Models.Services

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Services</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Classification)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Classification)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Fee)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Fee)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="ID" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Views/Service/Descriptions.cshtml
@model RazorPages.Models.Services

<h2>What type of spa service are you interested in?</h2>

<form name="spaServices" method="post">
    <div class="form-group">
        <label asp-for="Classification" class="form-label">Select a service from the list:</label>
        <select style="width:100px;" asp-for="Classification" asp-items="@(new SelectList(ViewBag.Classifications,"Classification","Classification"))"
                class="form-control"></select>
    </div>
    <button type="submit">Submit</button>

</form>

Views/Service/Details.cshtml
@model RazorPages.Models.Services

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Services</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Classification)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Classification)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Fee)
        </dt>
        <dd class="col-sm-10">
            @ViewBag.fee.ToString("C2")
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.ID">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

Views/Service/Edit.cshtml
@model RazorPages.Models.Services

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Services</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="ID" />
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Classification" class="control-label"></label>
                <input asp-for="Classification" class="form-control" />
                <span asp-validation-for="Classification" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Fee" class="control-label"></label>
                <input asp-for="Fee" class="form-control" />
                <span asp-validation-for="Fee" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Service/Index.cshtml
@model IEnumerable<RazorPages.Models.Services>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table bg-light">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Classification)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Fee)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Classification)
            </td>
            <td>
                @item.Fee.ToString("C2")
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.ID">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.ID">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.ID">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>

Views/Service/all.cshtml
@{
    ViewData["Title"] = "All Spa Services";
}

<div class="jumbotron bg-dark text-light row">
    <h1 class="col-md-12"> Spa Services</h1>
    <img src="~/Images/spaServices.jpg" alt="spa services" class="col-md-6 rounded-6 pr-md-4" />
    <ol class="col-md-6" >
        <li><a asp-fragment="full">Full-Day Treatment Package</a></li>
        <li><a asp-fragment="half">Half-Day Treatment Package</a></li>
        <li><a asp-fragment="two">Two-Hour Treatment Package</a></li>
        <li><a asp-fragment="one">One-Hour Treatment Package</a></li>
        <li><a asp-fragment="other">Other Services</a></li>
    </ol>
</div>

<h1 id="full ">Full-Day Treatment Package</h1>

<p>Includes all the following services:</p>

<ul>
    <li>
        Four Layer European Skin Care Treatment (80 minutes)
    </li>
    <li>
        Swedish Massage (110 minutes)
    </li>
    <li>
        Hot Stone Spa Pedicure with Paraffin Wax (80 minutes)
    </li>
    <li>
        Signature Manicure (50 minutes)
    </li>
    <li>
        Signature Pedicure (110 minutes)
    </li>
    <li>
        Hair styling
    </li>
    <li>
        Make-up
    </li>
</ul>

<p>Approximately 7 Hours </p>
<hr />
<h1 id="half">Half-Day Treatment Package</h1>

<p>Includes hair, makeup and two services of your choice:</p>

<ul>
    <li>
        Four Layer European Skin Care Treatment (80 minutes)
    </li>
    <li>
        Swedish Massage (110 minutes)
    </li>
    <li>
        Hot Stone Spa Pedicure with Paraffin Wax (80 minutes)
    </li>
    <li>
        Signature Manicure (50 minutes)
    </li>
    <li>
        Signature Pedicure (110 minutes)
    </li>

</ul>

<p>Approximately 4 Hours </p>

<hr />
<h1 id="two">Two-Hour Treatment Package</h1>

<p>Includes hair, makeup and one service of your choice:</p>

<ul>
    <li>
        Four Layer European Skin Care Treatment (80 minutes)
    </li>
    <li>
        Swedish Massage (110 minutes)
    </li>
    <li>
        Hot Stone Spa Pedicure with Paraffin Wax (80 minutes)
    </li>
    <li>
        Signature Manicure (50 minutes)
    </li>
    <li>
        Signature Pedicure (110 minutes)
    </li>
</ul>

<p>Approximately 2-3 Hours </p>

<hr />
<h1 id="one">One Hour Treatment Package</h1>

<p>Includes hair or makeup and manicure or pedicure</p>

<p>Approximately 1-2 Hours </p>
<hr />

<h1 id="other">Salon Packages</h1>
<h3>Cuts</h3>
<ul>
    <li>Full</li>
    <li>Bangs</li>
</ul>

<h3>Color</h3>
<ul>
    <li>Full</li>
    <li>Partial</li>
    <li>Roots</li>
</ul>

<h3>Other</h3>
<p>Please contact the salon to create your own special package</p>
<hr />

Views/Service/full.cshtml
<h1>Full-Day Treatment Package</h1>

<p>Includes all the following services:</p>

<ul>
    <li>
        Four Layer European Skin Care Treatment (80 minutes)
    </li>
    <li>
        Swedish Massage (110 minutes)
    </li>
    <li>
        Hot Stone Spa Pedicure with Paraffin Wax (80 minutes)
    </li>
    <li>
        Signature Manicure (50 minutes)
    </li>
    <li>
        Signature Pedicure (110 minutes)
    </li>
    <li>
        Hair styling
    </li>
    <li>
        Make-up
    </li>
</ul>

<p>Approximately 7 Hours </p>

<p>
    <a asp-controller="Service" asp-action="all">All Services</a>
</p>

Views/Service/half.cshtml
<h1>Half-Day Treatment Package</h1>

<p>Includes hair, makeup and two services of your choice:</p>

<ul>
    <li>
        Four Layer European Skin Care Treatment (80 minutes)
    </li>
    <li>
        Swedish Massage (110 minutes)
    </li>
    <li>
        Hot Stone Spa Pedicure with Paraffin Wax (80 minutes)
    </li>
    <li>
        Signature Manicure (50 minutes)
    </li>
    <li>
        Signature Pedicure (110 minutes)
     </li>

</ul>

<p>Approximately 4 Hours </p>

<p>
    <a asp-controller="Service" asp-action="all">All Services</a>
</p>

Views/Service/one.cshtml
<h1>One Hour Treatment Package</h1>

<p>Includes hair or makeup and manicure or pedicure</p>

<p>Approximately 1-2 Hours </p>

<p>
    <a asp-controller="Service" asp-action="all">All Services</a>
</p>

Views/Service/other.cshtml
<h1>Salon Packages</h1>
<h3>Cuts</h3>
<ul>
    <li>Full</li>
    <li>Bangs</li>
</ul>

<h3>Color</h3>
<ul>
    <li>Full</li>
    <li>Partial</li>
    <li>Roots</li>
</ul>

<h3>Other</h3>
<p>Please contact the salon to create your own special package</p>

<p>
    <a asp-controller="Service" asp-action="all">All Services</a>
</p>

Views/Service/two.cshtml
<h1>Two-Hour Treatment Package</h1>

<p>Includes hair, makeup and one service of your choice:</p>

<ul>
    <li>
        Four Layer European Skin Care Treatment (80 minutes)
    </li>
    <li>
        Swedish Massage (110 minutes)
    </li>
    <li>
        Hot Stone Spa Pedicure with Paraffin Wax (80 minutes)
    </li>
    <li>
        Signature Manicure (50 minutes)
    </li>
    <li>
        Signature Pedicure (110 minutes)
    </li>
</ul>

<p>Approximately 2-3 Hours </p>

<p>
    <a asp-controller="Service" asp-action="all">All Services</a>
</p>